FROM local/centos7-systemd
ARG REPO_SSH_KEY

RUN yum -y install openssh-server openssh-clients; systemctl enable sshd.service;
ADD $REPO_SSH_KEY /ssh/id_rsa
RUN chmod 0700 /ssh
RUN chmod 0600 /ssh/id_rsa
RUN eval `ssh-agent -s` && ssh-add /ssh/id_rsa
CMD ["/usr/sbin/init"]