---
- block:
  - name: Check repository directory state
    stat:
      path: '{{ repo_dest }}'
    register: repo_folder

  - name: Ensure repository directory exists with correct permissions
    file:
      path: '{{ repo_dest }}'
      owner: '{{ application_user }}'
      group: '{{ application_group }}'
      recurse: 'yes'
      state: 'directory'
      force: no
    become: yes
    when: repo_folder.stat.exists == false
    tags: download-repository

  - name: Fetch Download repository sources with git
    git:
      repo: '{{ repo_url }}'
      version: '{{ repo_version }}'
      force: 'no'
      key_file: '{{ repo_deploy_key }}'
      accept_hostkey: 'yes'
      dest: '{{ repo_dest }}'
    when: repo_install_method == 'pull'
    tags: download-repository

  - name: Push local Download repository
    copy:
      src: '{{ repo_src }}'
      dest: '{{ directory_source_root }}'
      force: no
    when: repo_install_method == 'push'
    tags: download-repository

  when: not delete_deployment

- name: Ensure repository is deleted
  file:
    path: '{{ repo_dest }}'
    state: 'absent'
  become: yes
  when: delete_deployment
  tags: download-repository
