---
- block:
  - name: Ensure nginx is installed
    yum:
      name: 'nginx'
      state: present
      enablerepo: "epel"
    become: yes
    when: "'nginx' not in ansible_facts.packages"
    tags: download-nginx

  - name: Ensure nginx service is enabled
    service:
      name: nginx
      state: started
      enabled: yes
    become: yes
    tags:
      - download-systemd-nginx

  - name: Ensure log directory exist with correct permissions
    file:
      path: '{{ directory_log }}'
      owner: '{{ application_user }}'
      group: '{{ application_group }}'
      state: 'directory'
      mode: '0755'
    become: yes
    tags:
      - download-nginx
      #- molecule-notest

  - name: Install Download Server Nginx configuration
    template:
      src: 'fairdata-download-server-nginx.conf.j2'
      dest: '/etc/nginx/conf.d/download-server.conf'
      mode: '0644'
    become: yes
    notify: Restart Nginx
    tags:
      - download-nginx
      - molecule-notest

  when: not delete_deployment
