---
- name: Install Download Generator service files
  template:
    src: '{{ item.file }}.j2'
    dest: '{{ item.dest }}'
    mode: '0644'
  with_items:
  - file: fairdata-download-generator.service
    dest: '/etc/systemd/system/fairdata-{{ instance_name }}-generator.service'
  - file: fairdata-download-generator.env
    dest: '{{ application_config_directory }}/fairdata-download-generator.env'
  become: yes
  notify: Restart Download Generator
  tags: generator-service

- name: Ensure Download Generator service is started
  systemd:
    name: 'fairdata-{{ instance_name }}-generator.service'
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  tags: generator-service
