---
- name: Install systemd files
  template:
    src: '{{ item.file }}.j2'
    dest: '{{ item.dest }}'
    mode: '0644'
  with_items:
  - file: fairdata-download-server.service
    dest: '/etc/systemd/system/fairdata-{{ instance_name }}-server.service'
  - file: fairdata-download-server.socket
    dest: '/etc/systemd/system/fairdata-{{ instance_name }}-server.socket'
  - file: fairdata-download-server.env
    dest: '{{ application_config_directory }}/fairdata-download-server.env'
  - file: fairdata-download-server-gunicorn.py
    dest: '{{ application_config_directory }}/fairdata-download-server-gunicorn.py'
  become: yes
  tags: download-server

- name: Ensure Download Server SystemD service is started
  systemd:
    name: '{{ item }}'
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  with_items:
  - 'fairdata-{{ instance_name }}-server.service'
  - 'fairdata-{{ instance_name }}-server.socket'
  tags: download-server
