---
- name: Ensure directories exist
  file:
    path: '{{ item }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
    mode: '0755'
  with_items:
  - '{{ application_config_directory }}'
  - '{{ application_log_directory }}'
  - '{{ application_runtime_directory }}'
  become: yes
  tags: download-config

- name: Remove old virtual environment
  file:
    path: '{{ application_runtime_directory }}/venv'
    state: 'absent'
  become: yes
  notify: Restart Download Server
  tags: download-config

- name: Install Download requirements in virtualenv with pip
  pip:
    requirements: '{{ repo_dest }}/requirements.txt'
    virtualenv: '{{ application_runtime_directory }}/venv'
    virtualenv_command: '{{ virtualenv_command }}'
  become: yes
  become_user: '{{ application_user }}'
  notify: Restart Download Server
  tags: download-config

- name: Install Download dev requirements in virtualenv with pip
  pip:
    requirements: '{{ repo_dest }}/requirements-dev.txt'
    virtualenv: '{{ application_runtime_directory }}/venv'
    virtualenv_command: '{{ virtualenv_command }}'
  when: application_environment != 'production'
  become: yes
  become_user: '{{ application_user }}'
  notify: Restart Download Server
  tags: download-config

- name: Copy service settings
  template:
    src: 'fairdata-download-service-settings.cfg.j2'
    dest: '{{ application_service_settings }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0640'
  become: yes
  when: daemonize_server
  tags: download-config

- name: Copy development environment file to Download repo
  template:
    src: 'fairdata-download-service-devel.env.j2'
    dest: '{{ repo_dest }}/.env'
    mode: '0640'
  become: yes
  when: not daemonize_server
  tags: download-config
