---
- name: Ensure Bindfs is installed
  yum:
    name: 'bindfs'
    state: 'latest'
  become: yes
  tags: download-mounts

- name: Ensure cache volume is owned by the application user
  file:
    path: '{{ cache_root }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
    mode: '0750'
  become: yes
  tags: download-mounts

- name: Ensure cache volume are mounted
  mount:
    path: '{{ cache_root }}'
    src: '{{ cache_device }}'
    fstype: ext4
    opts: auto
    state: mounted
  become: yes
  when: mount_volumes
  tags: download-mounts

- name: Check if ida storage is bind mounted
  mount:
    path: '{{ ida_storage_root }}'
    src: '{{ ida_storage_source }}'
    fstype: ext4
    state: present
  become: yes
  register: bind_mount_res
  tags: download-mounts

- name: Ensure ida bind mountpoint exists
  file:
    path: '{{ ida_storage_root }}'
    state: 'directory'
    mode: '0770'
  become: yes
  when: bind_mount_res.changed == True
  tags: download-mounts

- name: Bind mount IDA storage volume
  command: 'bindfs --resolve-symlinks --perms=a-w --mirror-only={{ application_user }} {{ ida_storage_source }} {{ ida_storage_root }}'
  become: yes
  when: bind_mount_res.changed == True
  tags: download-mounts
