---
- name: Include Download Service user tasks
  include_tasks: "download-user.yml"
  when: prepare_application
  tags: download-users

- name: Ensure Sqlite is installed
  yum:
    name: 'sqlite'
    state: 'latest'
  become: yes
  when: prepare_application
  tags: download-sqlite

- name: Include Download Service repository tasks
  include_tasks: "download-repository.yml"
  when: deploy_application
  tags: download-repository

- name: Include Download Service configuration tasks
  include_tasks: "download-config.yml"
  when: deploy_application
  tags: download-config

- name: Include Download Service SystemD tasks
  include_tasks: "download-systemd.yml"
  when: deploy_application
  tags: download-systemd

- name: Include Nginx tasks
  include_tasks: "download-nginx.yml"
  when: configure_nginx
  tags: download-nginx
