---
- name: Include Download Debug tasks
  include_tasks: "download-debug.yml"
  when: debug
  tags: download-debug

- name: Ensure sudo is installed
  yum:
    name: sudo
    state: present
  when: prepare_application
  tags: download-sudo

- name: Ensure git is installed
  yum:
    name: git
    state: present
  when: prepare_application
  tags: download-git

- name: Include Download Service user tasks
  include_tasks: "download-user.yml"
  when: prepare_application
  tags: download-users

- name: Ensure Sqlite is installed
  yum:
    name: 'sqlite'
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  when: prepare_application
  tags: download-sqlite

- name: install EPEL repo
  become: yes
  yum: name=epel-release state=present

- name: Ensure nginx is installed
  yum:
    name: 'nginx'
    state: present
    enablerepo: "epel"
  become: yes
  when: prepare_application
  tags: download-nginx

- name: Include Download Service repository tasks
  include_tasks: "download-repository.yml"
  when: deploy_application
  tags: download-repository

- name: Include Download Service configuration tasks
  include_tasks: "download-config.yml"
  when: deploy_application
  tags: download-config

- name: Include Download Service SystemD tasks
  include_tasks: "download-systemd.yml"
  when: deploy_application
  tags: download-systemd

- name: Include Nginx tasks
  include_tasks: "download-nginx.yml"
  when: configure_nginx
  tags: download-nginx
