---
- name: Restart Nginx
  systemd:
    name: 'nginx'
    state: 'restarted'
  become: yes
  when: ida_offline_sentinel_file.stat.exists == true

- name: Restart Download systemd Services
  systemd:
    name: '{{ instance_name }}-{{ item }}'
    state: 'restarted'
    daemon_reload: yes
  with_items:
    - 'server'
    - 'generator'
  become: yes
