---
- name: Restart Nginx
  systemd:
    name: 'nginx'
    state: 'restarted'
  become: yes

- name: Restart Download Server
  systemd:
    name: 'fairdata-{{ instance_name }}-server'
    state: 'restarted'
    daemon_reload: yes
  become: yes

- name: Restart Download Generator
  systemd:
    name: 'fairdata-{{ instance_name }}-generator'
    state: 'restarted'
    daemon_reload: yes
  become: yes
