---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:8



provisioner:
  name: ansible

  inventory:
    host_vars:
      instance:
        ansible_user: root
  config_options:
    defaults:
      remote_tmp: /tmp
      verbosity: 1
      local_tmp: /tmp
    ssh_connection:
      usetty: True
    diff:
      always: True
 # lint:
 #   name: ansible-lint
verifier:
  name: ansible
